services:

  diagnosis_gateway:
    image: diagnosis_gateway
    container_name: diagnosis_gateway
    networks:
        net:
          ipv4_address: 172.28.1.2
    environment:
      - VIEW_IP=172.28.1.6
      - VIEW_PORT=8082
      - PATIENT_IP=172.28.1.4
      - PATIENT_PORT=8081
      - NOTE_IP=172.28.1.3
      - NOTE_PORT=8083
      - RISK_IP=172.28.1.5
      - RISK_PORT=8085
      - GATEWAY_IP=172.28.1.2
      - GATEWAY_PORT=8084
    restart: always
    volumes:
      - ./diagnosis:/var/www/html
    ports:
      - "8084:8084"

  diagnosis_note:
      image: diagnosis_note
      container_name: diagnosis_note
      networks:
        net:
          ipv4_address: 172.28.1.3
      restart: always
      volumes:
          - ./diagnosis:/var/www/html
      ports:
          - "8083:8083"
      depends_on:
          - diagnosis_gateway

  diagnosis_patient:
    image: diagnosis_patient
    container_name: diagnosis_patient
    networks:
      net:
        ipv4_address: 172.28.1.4
    restart: always
    volumes:
      - ./diagnosis:/var/www/html
    ports:
      - "8081:8081"
    depends_on:
        - diagnosis_gateway

  diagnosis_risk:
    image: diagnosis_risk
    container_name: diagnosis_risk
    networks:
      net:
        ipv4_address: 172.28.1.5
    environment:
      - PATIENT_IP=172.28.1.4
      - PATIENT_PORT=8081
      - NOTE_IP=172.28.1.3
      - NOTE_PORT=8083
      - GATEWAY_IP=172.28.1.2
      - GATEWAY_PORT=8084
    restart: always
    volumes:
      - ./diagnosis:/var/www/html
    ports:
      - "8085:8085"
    depends_on:
        - diagnosis_gateway

  diagnosis_view:
    image: diagnosis_view
    container_name: diagnosis_view
    networks:
      net:
        ipv4_address: 172.28.1.6
    environment:
      - PATIENT_IP=172.28.1.4
      - PATIENT_PORT=8081
      - NOTE_IP=172.28.1.3
      - NOTE_PORT=8083
      - RISK_IP=172.28.1.5
      - RISK_PORT=8085
    restart: always
    volumes:
      - ./diagnosis:/var/www/html
    ports:
      - "8082:8082"
    depends_on:
        - diagnosis_gateway

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  db-volume:
  mongo-data:
    driver: local

